name: event_manager
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  google_sign_in: ^6.1.6
  provider: ^6.1.1
  image_picker: ^1.0.7
  shared_preferences: ^2.2.2
  fl_chart: ^0.65.0
  intl: ^0.19.0
  pdf: ^3.10.7
  printing: ^5.11.1
  share_plus: ^7.2.1
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.14.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/dmu_logo.png
    - assets/images/dmu_logo1.png
